[Hide_Plugin]
EQUAL,io.zhile.research.ide-eval-resetter
EQUAL,Nasller.License
EQUAL,nasller
# EQUAL,manifold.ij

[Hide_Package]
PREFIX,com.janetfilter
PREFIX,org.objectweb.asm

[Hide_Resource]
EQUAL,/6c81ec87e55d331c267262e892427a3d93d76683.txt
PREFIX,/com/janetfilter
# PREFIX,/com/novitechie

[Hide_Env]
EQUAL,IDEA_VM_OPTIONS
EQUAL,CLION_VM_OPTIONS
EQUAL,PHPSTORM_VM_OPTIONS
EQUAL,GOLAND_VM_OPTIONS
EQUAL,PYCHARM_VM_OPTIONS
EQUAL,WEBSTORM_VM_OPTIONS
EQUAL,WEBIDE_VM_OPTIONS
EQUAL,RIDER_VM_OPTIONS
EQUAL,DATAGRIP_VM_OPTIONS
EQUAL,RUBYMINE_VM_OPTIONS
EQUAL,APPCODE_VM_OPTIONS
EQUAL,DATASPELL_VM_OPTIONS
EQUAL,GATEWAY_VM_OPTIONS
EQUAL,JETBRAINS_CLIENT_VM_OPTIONS
EQUAL,JETBRAINSCLIENT_VM_OPTIONS
EQUAL,JANF_DEBUG
EQUAL,JANF_OUTPUT

[Hide_Property]
EQUAL,janf.debug
EQUAL,janf.output

[Ignore_Class]
EQUAL,com.janetfilter.core.utils.StringUtils
# EQUAL,com.janetfilter.core.utils.DateUtils
# EQUAL,com.janetfilter.core.attach.VMDescriptor
EQUAL,com.janetfilter.core.attach.VMSelector
# EQUAL,com.janetfilter.core.enums.RuleType
# EQUAL,com.janetfilter.core.plugin.PluginClassLoader
EQUAL,com.janetfilter.core.plugin.PluginConfig
# EQUAL,com.janetfilter.core.plugin.MyTransformer
# EQUAL,com.janetfilter.core.plugin.PluginManager
EQUAL,com.janetfilter.core.rulers.PrefixICRuler
EQUAL,com.janetfilter.core.rulers.SuffixRuler
EQUAL,com.janetfilter.core.Dispatcher

[Ignore_Resource]
EQUAL,/com/janetfilter/core/utils/StringUtils.class
# EQUAL,/com/janetfilter/core/utils/DateUtils.class
# EQUAL,/com/janetfilter/core/attach/VMDescriptor.class
EQUAL,/com/janetfilter/core/attach/VMSelector.class
# EQUAL,/com/janetfilter/core/enums/RuleType.class
# EQUAL,/com/janetfilter/core/plugin/PluginClassLoader.class
EQUAL,/com/janetfilter/core/plugin/PluginConfig.class
# EQUAL,/com/janetfilter/core/plugin/MyTransformer.class
# EQUAL,/com/janetfilter/core/plugin/PluginManager.class
EQUAL,/com/janetfilter/core/rulers/PrefixICRuler.class
EQUAL,/com/janetfilter/core/rulers/SuffixRuler.class
EQUAL,/com/janetfilter/core/Dispatcher.class
# EQUAL,/com/novitechie/placeholder